### ISSUE TITLE
Survey dialog remains open below the map

### ISSUE THREAD

**Issue by RyanTG** [russbiggs/spot-the-box#14]
_Tested in Firefox 79, desktop. Will test more browsers/configurations shortly._

After you've closed a survey dialog, the dialog actually remains visible, situated below the map (scroll down to see it).

![usps](https://user-images.githubusercontent.com/632682/90431801-6e584080-e07e-11ea-89c0-1e11358be2e8.png)

**Comment by russbiggs** [comment]
Can't reproduce this in firefox 79. Everything is being hidden as expected. Are you still seeing this issue?

**Comment by RyanTG** [comment]
I'm still waiting for the DNS http://spot-the-box.us/ to resolve. Will check more thoroughly once I can.

**Comment by RyanTG** [comment]
Yes, I was still seeing it on firefox 79 and chromium 84. My [PR](https://github.com/russbiggs/spot-the-box/pull/17) resolves this issue.
