### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by mikelmaron** [russbiggs/spot-the-box#23]
a LICENSE file in repo and a contribution statement on the website. Maybe MIT for the code and CC0 for the data (with a note that the original data is public domain via a federal agency and all contributions are CC0?)

**Comment by mikelmaron** [comment]
For opening modal "All correction/verification data added to this project is contributed and available on a CC0 basis"  with CCO linked to https://creativecommons.org/publicdomain/zero/1.0/

**Comment by mikelmaron** [comment]
contribution statement live

**Comment by russbiggs** [comment]
LICENSE added in ea771b3
