### ISSUE TITLE
Change color of symbols for color-blind accessiblity

### ISSUE THREAD

**Issue by frizatch** [russbiggs/spot-the-box#28]
Presently, it is a little hard to see the green vs blue dots. I propose a switch to the following color scheme pulled from colorbrewer2.org (see image) to accommodate color-blind people:

un-surveyed = #abd9e9
present = #2c7bb6
removed = #d7191c
inoperable = #fdae61

We could try to keep #004B77 (the postal blue!) over #2c7bb6 and shift the other colors appropriately

I didn't see in index.js that 'expression' was set up for inoperable yet. I'm happy to work on this issue if I'm in the right place.

![Capture](https://user-images.githubusercontent.com/20845777/90832423-fbabc700-e302-11ea-9bd2-f44d22137598.JPG)

**Comment by russbiggs** [comment]
Good catch on the missing value in the expression.  I'm always for making things more accessible! There's some new styling and discussion happening in a PR here.  I'd be interested in how we can incorporate color blind safe color scheme with the changes going on the in the PR #27

**Comment by planemad** [comment]
@frizatch thank you for the colors, they were implemented in #27. 

https://github.com/russbiggs/spot-the-box/blob/7b25a6c8a6c3b6b488bead0d0e60d52fc497a176/src/js/index.js#L9-L13. 

https://github.com/russbiggs/spot-the-box/blob/7b25a6c8a6c3b6b488bead0d0e60d52fc497a176/src/js/index.js#L155-L163

Although, i didn't bother to check if `inoperable` was the right property. @russbiggs ?

**Comment by planemad** [comment]
Ah and looks like i did not update the postal blue, so that could be something to try out.

**Comment by frizatch** [comment]
Thanks, I'm loving what you did with the symbology!

One *slight* consequence is it's a bit hard to spot the solo boxes out in the rural areas now with the hollow circles, but focused users, or those who know those locations will be able to spot them. I think this is an okay trade-off for the awesomeness in the added overall usability of the map.

**Comment by russbiggs** [comment]
```inoperable``` is the correct key thanks @planemad and @frizatch
