### ISSUE TITLE
Handle overlapping points

### ISSUE THREAD

**Issue by russbiggs** [russbiggs/spot-the-box#30]
Some points in the data set overlap since they have the exact same lat/lng. We need a way to disaggregate these and allow users to distinguish between overlapping points during survey

**Comment by russbiggs** [comment]
<img width="757" alt="Screen Shot 2020-09-01 at 9 10 18 PM" src="https://user-images.githubusercontent.com/8487728/91927774-95765b00-ec97-11ea-8c60-b8335f54c551.png">
 Current concept. on click if there is more than one feature a pop up shows and the user click which outlet they want to survey. @mikelmaron any thoughts?

**Comment by frizatch** [comment]
I like this pop-up with the mailbox codes a lot if:
- the intro instructions (I think I saw a redo showing this) point out these numbers with the pic + arrow in a way that can't be missed.
- the different codes appear in the pop-up in big enough buttons on mobile to easily bit with your finger.

Awesome work, Russ!

**Comment by russbiggs** [comment]
@frizatch Good idea on bigger buttons. I have implemented the how-to with the Location No/Outlet ID on the develop branch, i've got a red arrow pointing to the number to hopefully make that clear!

**Comment by frizatch** [comment]
Great! Yes, I saw that how-to mock-up in #32 I think. Perfect.

**Comment by ranatalus** [comment]
I think that's perfect! I only have minor changes to suggest:
1) Change is the punctuation/capitalization to:

"N collection boxes at this point.
Select one:"

2) Could we change the bullet points to reflect the dot legend we've already set up?

3) Keep interactable object spacing in mind; most standards are to have touchpoints that are, at minimum, 48x48px with at least 8px between them--and, ideally, having the entire area of text be interactable, not just the text itself (which makes for awkward finger targeting)

**Comment by russbiggs** [comment]
@ranatalus @frizatch I've given the list items 48px height and 8px spacing and implemented the color coding (great idea!). The entire area around the text (48px) is clickable. Any other thoughts?
<img width="549" alt="Screen Shot 2020-09-03 at 10 13 20 AM" src="https://user-images.githubusercontent.com/8487728/92140417-4d0d8900-edce-11ea-872b-790a7a8417b5.png">

**Comment by ranatalus** [comment]
Nope! Looks good to me.

**Comment by frizatch** [comment]
Yep, lovely!
