### ISSUE TITLE
Add how-to modal

### ISSUE THREAD

**Issue by russbiggs** [russbiggs/spot-the-box#32]
Add a modal to help guide how-to find and map collection boxes with spot-the-box

**Comment by ranatalus** [comment]
Modal should include:
-Explanation of color coding
-Guide on bringing up an individual box's page
-Reminder to hit "save" after updating a box
-quick photo upload instructions (once photos are implemented)

**Comment by russbiggs** [comment]
Current mockup:
![Spot the Box](https://user-images.githubusercontent.com/8487728/91679951-eefb5000-eb06-11ea-8932-8de2ef200c8b.png)

**Comment by mikelmaron** [comment]
this look awesome @russbiggs
