### ISSUE TITLE
Font discussion

### ISSUE THREAD

**Issue by mikelmaron** [russbiggs/spot-the-box#9]
* ~~This thing needs a name~~ SPOT THE BOX
 * What font should we use?
 * ~~Add opening dialog with instructions~~
 * ~~hamburger menu should show opening dialog or more full about~~ (now info icon)

**Comment by russbiggs** [comment]
I've set the font to Poppins for now, so its something better than the default sans serif. Open to other suggestions still.

**Comment by frizatch** [comment]
After hitting "Get Started" (on mobile, Chrome or whatever browser), it would be good to have initial instruction text on the map that says, "tap or click on a mailbox location to submit feedback" ... maybe with a "don't show again" option.

**Comment by ranatalus** [comment]
@russbiggs could use the USPS font itself (Postmaster): https://www.ffonts.net/Postmaster.font?text=Spot+the+box

**Comment by ranatalus** [comment]
@frizatch I'm going to break that out into a separate issue

**Comment by russbiggs** [comment]
I think Postmaster could work for the title but would rather keep the other text something more legible.  Here's a preview with Postmaster.  Thoughts?
<img width="281" alt="Screen Shot 2020-08-19 at 12 13 04 PM" src="https://user-images.githubusercontent.com/8487728/90673801-78f90e00-e215-11ea-8f18-a2f516757cba.png">

**Comment by russbiggs** [comment]
PostMaster added in af07a6a
